server:
  port: 20002

---

spring:
  profiles: default

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: test

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

logging:
  level:
    root: DEBUG
  file:
    name: logs/${spring.application.name}.log